In [13]:
with open('One.txt')as mytext:
    words_one = mytext.read().lower().split()
    uni_words_one = set(words_one)

In [14]:
uni_words_one

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'dogs',
 'furry',
 'is',
 'our',
 'pets',
 'story',
 'this'}

In [15]:
with open('Two.txt')as mytext:
    words_two = mytext.read().lower().split()
    uni_words_two = set(words_two)

In [16]:
uni_words_two

{'a',
 'about',
 'catching',
 'fun',
 'is',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [17]:
all_uni_words = set()
all_uni_words.update(uni_words_one)

In [18]:
all_uni_words.update(uni_words_two)

In [19]:
all_uni_words

{'a',
 'about',
 'animals',
 'are',
 'canine',
 'catching',
 'dogs',
 'fun',
 'furry',
 'is',
 'our',
 'pets',
 'popular',
 'sport',
 'story',
 'surfing',
 'this',
 'water',
 'waves'}

In [22]:
full_vocab = dict()
i = 0

for word in all_uni_words:
    full_vocab[word] = i
    i = i + 1

In [23]:
full_vocab

{'catching': 0,
 'sport': 1,
 'story': 2,
 'is': 3,
 'our': 4,
 'furry': 5,
 'about': 6,
 'surfing': 7,
 'pets': 8,
 'are': 9,
 'canine': 10,
 'this': 11,
 'animals': 12,
 'water': 13,
 'waves': 14,
 'a': 15,
 'popular': 16,
 'dogs': 17,
 'fun': 18}

In [24]:
one_freq = [0]*len(full_vocab)
two_freq = [0]*len(full_vocab)
all_words = ['']*len(full_vocab)

In [28]:
one_freq

[0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0]

In [29]:
with open('One.txt')as f:
    one_text = f.read().lower().split()

In [30]:
for word in one_text:
    word_ind = full_vocab[word]
    one_freq[word_ind] += 1

In [31]:
one_freq

[0, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 0, 1, 0, 2, 0]

In [32]:
with open('Two.txt')as f:
    two_text = f.read().lower().split()

In [33]:
for word in two_text:
    word_ind = full_vocab[word]
    two_freq[word_ind] += 1

In [35]:
two_freq

[1, 1, 1, 3, 0, 0, 1, 2, 0, 0, 0, 1, 0, 1, 1, 1, 1, 0, 1]

In [36]:
all_words

['', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '', '']

In [37]:
for word in full_vocab:
    word_ind = full_vocab[word]
    all_words[word_ind] = word

In [38]:
all_words

['catching',
 'sport',
 'story',
 'is',
 'our',
 'furry',
 'about',
 'surfing',
 'pets',
 'are',
 'canine',
 'this',
 'animals',
 'water',
 'waves',
 'a',
 'popular',
 'dogs',
 'fun']

In [39]:
import pandas as pd
bow = pd.DataFrame(data=[one_freq,two_freq], columns=all_words)

In [40]:
bow

catching  sport  story  is  our  furry  about  surfing  pets  are  canine  \
0         0      0      1   1    1      1      1        0     1    1       1   
1         1      1      1   3    0      0      1        2     0    0       0   

   this  animals  water  waves  a  popular  dogs  fun  
0     1        1      0      0  1        0     2    0  
1     1        0      1      1  1        1     0    1

In [41]:
text = ['This is a line',
       'This is another line',
       'Completely different line']

In [52]:
from sklearn.feature_extraction.text import CountVectorizer,TfidfTransformer

In [55]:
cv = CountVectorizer()

In [56]:
sparse_matrix = cv.fit_transform(text)

In [57]:
sparse_matrix.todense()

matrix([[0, 0, 0, 1, 1, 1],
        [1, 0, 0, 1, 1, 1],
        [0, 1, 1, 0, 1, 0]])

In [58]:
cv.vocabulary_

{'this': 5, 'is': 3, 'line': 4, 'another': 0, 'completely': 1, 'different': 2}

In [59]:
tfidf = TfidfTransformer()

In [60]:
sparse_matrix

<3x6 sparse matrix of type '<class 'numpy.int64'>'
	with 10 stored elements in Compressed Sparse Row format>

In [61]:
results = tfidf.fit_transform(sparse_matrix) # BOW --->TF -IDF

In [63]:
results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])

In [64]:
from sklearn.feature_extraction.text import TfidfVectorizer

In [65]:
tv = TfidfVectorizer()

In [66]:
tv_results = tv.fit_transform(text)

In [67]:
tv_results.todense()

matrix([[0.        , 0.        , 0.        , 0.61980538, 0.48133417,
         0.61980538],
        [0.63174505, 0.        , 0.        , 0.4804584 , 0.37311881,
         0.4804584 ],
        [0.        , 0.65249088, 0.65249088, 0.        , 0.38537163,
         0.        ]])